# dcat_generator.py
import json
import logging
from pathlib import Path
from rdflib import Graph, Namespace, URIRef, Literal, Dataset, BNode
from rdflib.namespace import DCTERMS, DCAT, FOAF, RDF, XSD, SKOS
from datetime import date

# Define necessary namespaces
DCATDE = Namespace("http://dcat-ap.de/def/dcatde/")
VCARD = Namespace("http://www.w3.org/2006/vcard/ns#")

_DCAT_TEMPLATE_PATH = Path(__file__).resolve().parents[1] / "templates" / "dcat_catalog.json"
_FALLBACK_DCAT_TEMPLATE = {
    "catalog": {
        "title": "Data Catalog",
        "description": "This catalog describes datasets generated by the Lab Data Toolkit.",
    },
    "themes": {
        "AGRI – Agriculture, fisheries, forestry and food": "http://publications.europa.eu/resource/authority/data-theme/AGRI",
        "ECON – Economy and finance": "http://publications.europa.eu/resource/authority/data-theme/ECON",
        "EDUC – Education, culture and sport": "http://publications.europa.eu/resource/authority/data-theme/EDUC",
        "ENER – Energy": "http://publications.europa.eu/resource/authority/data-theme/ENER",
        "ENVI – Environment": "http://publications.europa.eu/resource/authority/data-theme/ENVI",
        "GOVE – Government and public sector": "http://publications.europa.eu/resource/authority/data-theme/GOVE",
        "HEAL – Health": "http://publications.europa.eu/resource/authority/data-theme/HEAL",
        "INTR – International issues": "http://publications.europa.eu/resource/authority/data-theme/INTR",
        "JUST – Justice, legal system and public safety": "http://publications.europa.eu/resource/authority/data-theme/JUST",
        "REGI – Regions and cities": "http://publications.europa.eu/resource/authority/data-theme/REGI",
        "SOCI – Population and society": "http://publications.europa.eu/resource/authority/data-theme/SOCI",
        "TECH – Science and technology": "http://publications.europa.eu/resource/authority/data-theme/TECH",
        "TRAN – Transport": "http://publications.europa.eu/resource/authority/data-theme/TRAN",
    },
    "licenses": {
        "CC BY 4.0": "http://creativecommons.org/licenses/by/4.0/",
        "CC0 1.0": "http://creativecommons.org/publicdomain/zero/1.0/",
        "Data Use Agreement for Official Statistics": "http://dcat-ap.de/def/licenses/official",
        "CC-BY-4.0": "https://creativecommons.org/licenses/by/4.0/",
    },
    "media_types": {
        "turtle": "text/turtle",
        "nquads": "application/n-quads",
        "json-ld": "application/ld+json",
        "xml": "application/rdf+xml",
        "pretty-xml": "application/rdf+xml",
        "trig": "application/trig",
    },
}


def _load_dcat_template():
    try:
        payload = json.loads(_DCAT_TEMPLATE_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        payload = {}
    template = {**_FALLBACK_DCAT_TEMPLATE, **(payload if isinstance(payload, dict) else {})}
    for key in ("themes", "licenses", "media_types"):
        value = template.get(key)
        if not isinstance(value, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in value.items()):
            template[key] = _FALLBACK_DCAT_TEMPLATE[key]
    catalog = template.get("catalog")
    if not isinstance(catalog, dict):
        template["catalog"] = _FALLBACK_DCAT_TEMPLATE["catalog"]
    else:
        template["catalog"] = {**_FALLBACK_DCAT_TEMPLATE["catalog"], **catalog}
    return template


_DCAT_TEMPLATE = _load_dcat_template()
DCAT_CATALOG_DEFAULTS = dict(_DCAT_TEMPLATE["catalog"])
THEMES = dict(_DCAT_TEMPLATE["themes"])
LICENSES = dict(_DCAT_TEMPLATE["licenses"])
MEDIA_TYPES = dict(_DCAT_TEMPLATE["media_types"])

def display_dcat_builder():
    """Deprecated placeholder for the removed Python DCAT form.

    DCAT metadata is now configured in the React/Material UI frontend and
    generated through ``create_dcat_catalog`` in the Python backend service.
    """
    logging.warning("display_dcat_builder is deprecated; use the MUI RDF Generator workflow instead.")
    return None


def create_dcat_catalog(
    rdf_graph: Graph,
    skos_graph: Graph,
    rdf_format: str,
    data_graph_uri_str: str,
    metadata_config: dict,
    default_namespace: str
) -> str:
    """
    Generates a DCAT catalog in TriG format, including the SKOS vocabulary.

    Args:
        rdf_graph: The ConjunctiveGraph containing the main data.
        skos_graph: The ConjunctiveGraph containing the SKOS vocabulary.
        rdf_format: The format of the original data (e.g., 'turtle').
        data_graph_uri_str: The URI for the named graph containing the data.
        metadata_config: A dictionary with all the required DCAT metadata.

    Returns:
        A string containing the full catalog in TriG format.
    """
    catalog_trig, _metadata_ttl = create_dcat_catalog_bundle(
        rdf_graph=rdf_graph,
        skos_graph=skos_graph,
        rdf_format=rdf_format,
        data_graph_uri_str=data_graph_uri_str,
        metadata_config=metadata_config,
        default_namespace=default_namespace,
    )
    return catalog_trig


def create_dcat_catalog_bundle(
    rdf_graph: Graph,
    skos_graph: Graph,
    rdf_format: str,
    data_graph_uri_str: str,
    metadata_config: dict,
    default_namespace: str
) -> tuple[str, str]:
    """Generate the full DCAT catalog TriG plus standalone metadata Turtle."""
    ds = Dataset()
    ds.bind("dct", DCTERMS)
    ds.bind("dcat", DCAT)
    ds.bind("dcatde", DCATDE)
    ds.bind("foaf", FOAF)
    ds.bind("vcard", VCARD)
    ds.bind("skos", SKOS)

    EX = Namespace(default_namespace)
    ds.bind("ex", EX)

    metadata_graph_uri = EX["graph/dcat-metadata"]
    meta_graph = ds.graph(identifier=metadata_graph_uri)
    data_graph_uri = URIRef(data_graph_uri_str)

    try:
        # 1. Process the main data graph
        source_graph = rdf_graph
        if data_graph_uri_str:
            source_context = source_graph.get_context(URIRef(data_graph_uri_str))
            if source_context:
                target_data_graph = ds.graph(identifier=data_graph_uri)
                for triple in source_context:
                    target_data_graph.add(triple)
            else:
                logging.warning(f"DCAT Gen: Named graph '{data_graph_uri_str}' not found in source graph.")
        else:
            for triple in source_graph.default_context:
                ds.default_context.add(triple)
        for prefix, namespace in source_graph.namespaces():
            ds.bind(prefix, namespace)

        # 2. Merge the SKOS vocabulary graph
        if skos_graph:
            for skos_context in skos_graph.contexts():
                skos_graph_id = skos_context.identifier
                target_skos_graph = ds.graph(identifier=skos_graph_id)
                for triple in skos_context:
                    target_skos_graph.add(triple)
                for prefix, namespace in skos_context.namespace_manager.namespaces():
                    if prefix not in ds.namespace_manager:
                        ds.bind(prefix, namespace)
            logging.info("Merged SKOS vocabulary into the DCAT dataset.")

    except Exception as e:
        logging.error(f"Error processing graphs for DCAT generation: {e}")
        raise

    catalog_uri = EX["catalog"]
    dataset_uri = data_graph_uri+"dataset/main"
    distribution_uri = data_graph_uri+"distribution/main"
    publisher_uri = URIRef(metadata_config["publisher_uri"])

    # Catalog
    meta_graph.add((catalog_uri, RDF.type, DCAT.Catalog))
    meta_graph.add((catalog_uri, DCTERMS.title, Literal(DCAT_CATALOG_DEFAULTS["title"], lang="en")))
    meta_graph.add((catalog_uri, DCTERMS.publisher, publisher_uri))
    meta_graph.add((catalog_uri, DCAT.dataset, dataset_uri))
    meta_graph.add((catalog_uri, DCTERMS.description, Literal(DCAT_CATALOG_DEFAULTS["description"], lang="en")))
    meta_graph.add((catalog_uri, DCTERMS.issued, Literal(date.today().isoformat(), datatype=XSD.date)))

    # Publisher
    meta_graph.add((publisher_uri, RDF.type, FOAF.Organization))
    meta_graph.add((publisher_uri, FOAF.name, Literal(metadata_config["publisher_name"])))

    # Dataset
    meta_graph.add((dataset_uri, RDF.type, DCAT.Dataset))
    meta_graph.add((dataset_uri, DCTERMS.title, Literal(metadata_config["title"], lang="en")))
    meta_graph.add((dataset_uri, DCTERMS.description, Literal(metadata_config["description"], lang="en")))
    meta_graph.add((dataset_uri, DCTERMS.publisher, publisher_uri))
    meta_graph.add((dataset_uri, DCTERMS.issued, Literal(date.today().isoformat(), datatype=XSD.date)))
    meta_graph.add((dataset_uri, DCTERMS.modified, Literal(date.today().isoformat(), datatype=XSD.date)))
    meta_graph.add((dataset_uri, DCTERMS.license, URIRef(LICENSES[metadata_config["license"]])))
    meta_graph.add((dataset_uri, DCAT.distribution, distribution_uri))

    # Keywords
    for kw in metadata_config.get("keywords", []):
        meta_graph.add((dataset_uri, DCAT.keyword, Literal(kw, lang="en")))

    # Identifier
    if metadata_config.get("identifier"):
        meta_graph.add((dataset_uri, DCTERMS.identifier, Literal(metadata_config["identifier"])))

    # Creator
    for author in metadata_config.get("creator", []):
        meta_graph.add((dataset_uri, DCTERMS.creator, Literal(author)))

    # Access Rights
    access_rights_uri = f"http://publications.europa.eu/resource/authority/access-right/{metadata_config['access_rights']}"
    meta_graph.add((dataset_uri, DCTERMS.accessRights, URIRef(access_rights_uri)))

    # Contact Point
    if metadata_config.get("contact_point"):
        contact_val = metadata_config["contact_point"]
        if contact_val.startswith("http") or contact_val.startswith("mailto:"):
            meta_graph.add((dataset_uri, DCAT.contactPoint, URIRef(contact_val)))
        else:
            # Create a simple vCard BNode if it's just text/email without mailto
            contact_bnode = BNode()
            meta_graph.add((contact_bnode, RDF.type, VCARD.Individual))
            meta_graph.add((contact_bnode, VCARD.hasEmail, Literal(contact_val)))
            meta_graph.add((dataset_uri, DCAT.contactPoint, contact_bnode))

    # Themes
    for theme_name in metadata_config.get("themes", []):
        if theme_name in THEMES:
            meta_graph.add((dataset_uri, DCAT.theme, URIRef(THEMES[theme_name])))

    
    # Publication reference linking
    if metadata_config.get("link_reference") and metadata_config.get("reference_data"):
        reference_data = metadata_config["reference_data"]
        reference_graph = reference_data.get("graph")
        
        if reference_graph:
            # Add the reference graph to the dataset
            reference_graph_uri = EX["graph/publication-reference"]
            ref_graph = ds.graph(identifier=reference_graph_uri)
            
            # Copy triples from the reference graph
            for triple in reference_graph:
                ref_graph.add(triple)
            
            # Copy namespaces
            for prefix, namespace in reference_graph.namespaces():
                if prefix not in ds.namespace_manager:
                    ds.bind(prefix, namespace)
            
            # Find the work URI from the reference graph (should be the subject with rdf:type soa:Work)
            work_uri = None
            SOA = Namespace("https://semopenalex.org/ontology/")
            DCT = Namespace("http://purl.org/dc/terms/") 
            for subj, pred, obj in reference_graph:
                if pred == DCT.abstract and obj != "":
                    work_uri = subj
                    break
            
            if work_uri:
                # Link the dataset to the publication using dcterms:isReferencedBy
                meta_graph.add((dataset_uri, DCTERMS.isReferencedBy, work_uri))
                logging.info(f"Linked dataset {dataset_uri} to publication {work_uri}")
            else:
                # Fallback: try to find any subject that looks like a work
                for subj, pred, obj in reference_graph:
                    if "work" in str(subj).lower():
                        meta_graph.add((dataset_uri, DCTERMS.isReferencedBy, subj))
                        logging.info(f"Linked dataset {dataset_uri} to publication {subj} (fallback)")
                        break

    # Distribution
    distribution_media_type = MEDIA_TYPES.get(rdf_format, "text/plain")
    
    # Serialize the data graph to calculate its byte size
    try:
        data_graph_content = ds.get_context(data_graph_uri).serialize(format=rdf_format)
        byte_size = len(data_graph_content)
    except Exception:
        # Fallback if serialization for size calculation fails
        byte_size = 0
        logging.warning("Could not determine byte size for DCAT distribution.")

    meta_graph.add((distribution_uri, RDF.type, DCAT.Distribution))
    meta_graph.add((distribution_uri, DCAT.accessURL, URIRef(data_graph_uri_str)))
    meta_graph.add((distribution_uri, DCTERMS.title, Literal(f"Distribution of {metadata_config['title']} in {rdf_format} format", lang="en")))
    meta_graph.add((distribution_uri, DCTERMS.license, URIRef(LICENSES[metadata_config["license"]])))
    meta_graph.add((distribution_uri, DCAT.mediaType, URIRef(f"http://www.iana.org/assignments/media-types/{distribution_media_type}")))
    meta_graph.add((distribution_uri, DCAT.byteSize, Literal(byte_size, datatype=XSD.decimal)))

    # Also return the standalone DCAT metadata for separate download
    dcat_metadata_ttl = meta_graph.serialize(format="turtle")

    return ds.serialize(format="trig"), dcat_metadata_ttl
